# Generated by Django 3.1.2 on 2020-10-23 09:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('href', models.URLField(help_text='A link to the Spotify Web API endpoint providing full details.', max_length=1024, verbose_name='href')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='title')),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('compilation', 'Compilation')], default='album', help_text='The type of the album: one of “album”, “single”, or “compilation”.', max_length=11, verbose_name='album_type')),
                ('available_in_france', models.BooleanField(default=True, verbose_name='available_in_france')),
                ('release_date', models.DateField(default=datetime.date.today, help_text='Release date of the album.', verbose_name='Release_date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('href', models.URLField(help_text='A link to the Spotify Web API endpoint providing full details.', max_length=1024, verbose_name='href')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(blank=True, max_length=512, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('href',), name='Spotify API unicity for artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, help_text='List of artists that have played on the album.', related_name='albums', to='api.Artist', verbose_name='artists'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('href',), name='Spotify API unicity for album'),
        ),
    ]
